spring.application.name=Java_Final_Assignment
spring.datasource.url=jdbc:mysql://localhost:3305/elite_performance
spring.datasource.username=root
spring.datasource.password=root123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.jpa.defer-datasource-initialization=true
 spring.jpa.show-sql=true

server.error.include-message=always